spring:
  kafka:
    security:
      protocol: SSL
    bootstrap-servers: my-cluster-kafka-bootstrap:9093
    ssl:
      trust-store-location: file:///tmp/secret/truststore.p12
      trust-store-password: ${TRUSTSTORE_PASSWORD}
      trust-store-type: PKCS12
      key-store-location:  file:///tmp/secret/keystore.p12
      key-store-password: ${KEYSTORE_PASSWORD}
      key-store-type: PKCS12
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer